In [1]:
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
from LinearRegression import getData
X, y = getData("50_Startups.csv")

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool
   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


In [3]:
print("Input Shape: {}\nOutput Shape: {}".format(X.shape, y.shape))

Input Shape: (50, 4)
Output Shape: (50, 1)


In [4]:
m = X.shape[0] # Number of training examples

#Adding intercept column
X = np.hstack([np.ones((m,1)), X])

In [5]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [6]:
print("Training Input Shape: {}\tTraining Output Shape: {}".format(X_tr.shape, y_tr.shape))
print("Testing Input Shape: {}\tTesting Output Shape: {}".format(X_te.shape, y_te.shape))

Training Input Shape: (40, 5)	Training Output Shape: (40, 1)
Testing Input Shape: (10, 5)	Testing Output Shape: (10, 1)


In [7]:
from sklearn.preprocessing import LabelEncoder
lbl_x = LabelEncoder()
lbl_x.fit(X[:, -1])
X[:, -1] = lbl_x.transform(X[:, -1])

In [8]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features = [-1])
X = ohe.fit_transform(X).toarray()

/home/vivek/myenv/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/vivek/myenv/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:390: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [9]:
print(X[:5])

[[0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 1.6534920e+05
  1.3689780e+05 4.7178410e+05]
 [1.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 1.6259770e+05
  1.5137759e+05 4.4389853e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.0000000e+00 1.5344151e+05
  1.0114555e+05 4.0793454e+05]
 [0.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00 1.4437241e+05
  1.1867185e+05 3.8319962e+05]
 [0.0000000e+00 1.0000000e+00 0.0000000e+00 1.0000000e+00 1.4210734e+05
  9.1391770e+04 3.6616842e+05]]


In [10]:
# Removing Dummy variable
X = X[:, 1:]

In [11]:
# Intercept Column
X = np.hstack([np.ones((m,1)), X])

In [12]:
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [13]:
from sklearn.preprocessing import StandardScaler
scl_x = StandardScaler()
scl_y = StandardScaler()

In [14]:
X_tr[:, 3:] = scl_x.fit_transform(X_tr[:, 3:])
X_te[:, 3:] = scl_x.transform(X_te[:, 3:])

y_tr = scl_y.fit_transform(y_tr)
y_te = scl_y.transform(y_te)

In [40]:
from LinearRegression import LinearRegression as LRscratch
lr = LRscratch(max_iter = 10000)
lr.fit(X_tr, y_tr)

In [41]:
y_pred = lr.predict(X_te)

In [42]:
print(y_pred)

[[ 0.25816802]
 [-0.74819571]
 [-0.38501547]
 [-1.67013132]
 [ 0.31570373]
 [-1.56034945]
 [-0.14245599]
 [-0.36172655]
 [-0.43509405]
 [-0.06157054]]


In [43]:
print(scl_y.inverse_transform(y_te))

[[134307.35]
 [ 81005.76]
 [ 99937.59]
 [ 64926.08]
 [125370.37]
 [ 35673.41]
 [105733.54]
 [107404.34]
 [ 97427.84]
 [122776.86]]


In [44]:
print(scl_y.inverse_transform(y_pred))

[[126363.22926199]
 [ 84608.73959864]
 [ 99677.25307384]
 [ 46357.21057614]
 [128750.41211302]
 [ 50912.11056881]
 [109741.15671383]
 [100643.5210081 ]
 [ 97599.47010329]
 [113097.13080099]]
